### PR TITLE
Added HTR image gathering pipeline to examples/README.md

### PR DESCRIPTION
**Pull request by tardis-forever**
Moved pipeline to separate repo, added links to it to examples README.

### CLA
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

### CODE REVIEW

**Comment by tulinev** [comment]
@tardis-forever, could you please merge your commit into `autosync` branch

**Comment by tardis-forever** [comment]
I changed branch to `autosync` and resolved merge conflicts. However, I do not have merge access to the repository and cannot merge changes. Or have I misunderstood you about what needed to be done?

**Comment by Losik** [comment]
@arcadia-devtools Ship it!

**Comment by Losik** [comment]
> I changed branch to `autosync` and resolved merge conflicts. However, I do not have merge access to the repository and Hi, Sorry for the delay; we will merge your pull request in a couple of days.

Our inner repository is configured to upload commits to GitHub automatically, but not the other way round. So, merging external pull requests is quite a pain. We are waiting for our devtools team to set up the automatic bidirectional sync configuration, and we'll be ready to go.

**Pull request merged**
