### PR TITLE
fix "op" is not defined

### PR DESCRIPTION
**Pull request by ZackPashkin**
fix "op" is not defined line 38

### CODE REVIEW

**Comment by Losik** [comment]
Thank you for noticing and fixing the problem! 

We'll be more than happy to accept your pull request after resolving some legal formalities. Our legal team requires all external contributers to accept the terms of CLA before we can merge their code. We kindly ask you to do so by leaving a comment (you can find the template in [CONTRIBUTING.md](https://github.com/Toloka/toloka-kit/blob/main/CONTRIBUTING.md#provide-contributions))

**Comment by ZackPashkin** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

**Comment by Losik** [comment]
@ZackPashkin , I had a closer look at your patch and understood that we actually generate documentation automatically from docstrings by our internal tools. I guess it's time to open-source them to this repo as well, but meanwhile, would you be so kind to fix [the docstring](https://github.com/Toloka/toloka-kit/blob/autosync/src/client/__init__.py#L2041) as well?

I also changed merge branch from `main` to `autosync`. It's our main development branch. It seems that something went wrong, cause for this branch there should be no Python 3.6 tests. I guess that failed tests are a result of a glitch in GitHub's testing mechanics and everything will hopefully get back to normal with an upcomming commit.

**Comment by ZackPashkin** [comment]
Done! https://github.com/Toloka/toloka-kit/pull/55

**Comment by Losik** [comment]
Closed this pull request in favour of #55

**Pull request closed without merging**
