### PR TITLE
Added example for handwriting images gathering pipeline

### PR DESCRIPTION
**Pull request by tardis-forever**
## Added example for handwriting images gathering pipeline. 

Main code is provided in `handwriting-gathering.ipynb`. With provided data and images one can re-run the whole pipeline for French. Code can be reused for any other language provided sample training photos are collected for training and the project#1 instructions are translated to that language (optionally, you can use English instructions that are also provided). 

### Structure:

- `data` contains sample sentences that can be reused instead of scraping
- `instructions` contains instructions for the projects and images for them
- `img` contains illustrations for the notebook
- `corpus.py` contains sample class for Wikipedia dump sentence extraction
- `requirements.txt`  contains all the requirements for the pipeline
- `handwriting-gathering.ipynb` contains main code for the pipeline

### CLA
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

### CODE REVIEW

**Comment by Losik** [comment]
Hi, Alexandra

It's really awesome, that you were able to build such an amazing project on top of Toloka-Kit!

Unfortunately, we as a team decided that we will not accept external projects as part of our repository at the moment. It will be hard for us to maintain and make it harder for their original authors to enhance.

Nevertheless, we would be thrilled to add your project to our examples lists at https://github.com/Toloka/toloka-kit/blob/main/examples/README.md. You can add a new pull request yourself, or we could do that for you if you'd like that.

**Comment by tardis-forever** [comment]
Hi!

In order to add project to the list of examples, should I move all the data from this fork to separate Github repo, and after that create new pull request for README with added links?

**Comment by Losik** [comment]
Yes, our belief is that external projects should have dedicated repositories. Here is an example of one such repo https://github.com/noath/asr-datasets-pipeline

**Comment by tardis-forever** [comment]
Moved to https://github.com/Toloka/toloka-kit/pull/25

**Pull request closed without merging**
